

[common]
flags =
	-g -O2
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_NIMBLE_CPP_LOG_LEVEL=4
	-DNIMBLE_CPP_LOG_LEVEL=4
	; -DCONFIG_BT_NIMBLE_EXT_ADV

[env]
build_type = debug
debug_tool = esp-builtin
debug_init_break = tbreak app_main
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
lib_deps =
    https://github.com/h2zero/NimBLE-Arduino#2.2.3

[env:atom-s3u]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	-DARDUINO_ATOMS3U
    -DARDUINO_USB_CDC_ON_BOOT=1
	${common.flags}


; board = m5stack-coreS3
[env:m5stamp-c3u]
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.partitions = huge_app.csv
board_build.variant = esp32c3
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.arduino.ldscript = esp32c3_out.ld
build_unflags =
	-DARDUINO_ESP32_DEV
build_flags =
	${common.flags}
	-DM5STAMP_C3U
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

[env:seed-c6]
board = seeed_xiao_esp32c6
build_flags =
	${common.flags}
