

[common]
flags =
	-g -O2
	-DCORE_DEBUG_LEVEL=3
	-DCONFIG_NIMBLE_CPP_LOG_LEVEL=1
	-DNIMBLE_CPP_LOG_LEVEL=1

[env]
build_type = debug
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.12/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip

lib_deps =
    https://github.com/h2zero/NimBLE-Arduino#master
	https://github.com/mathertel/OneButton

[env:atom-s3u]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	-DARDUINO_ATOMS3U
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DBUTTON_PIN=41
	${common.flags}


[env:m5stamp-c3u]
debug_tool = esp-builtin
debug_init_break = tbreak app_main
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.partitions = huge_app.csv
board_build.variant = esp32c3
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.arduino.ldscript = esp32c3_out.ld
build_unflags =
	-DARDUINO_ESP32_DEV
build_flags =
	${common.flags}
	-DM5STAMP_C3U
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DBUTTON_PIN=9

[env:m5stick-c-plus]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1
lib_ldf_mode = deep
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
monitor_speed = 115200
build_flags =
	${common.flags}
	-DM5STICK_CPLUS
	-DBUTTON_PIN=37