


[env]
build_type = debug
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
lib_deps =
    https://github.com/h2zero/NimBLE-Arduino#2.2.3

[env:atom-s3u]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	-g -O2
	-DCORE_DEBUG_LEVEL=4
	-DARDUINO_ATOMS3U
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_NIMBLE_CPP_LOG_LEVEL=4
	-DNIMBLE_CPP_LOG_LEVEL=4

; board = m5stack-coreS3
